### ISSUE TITLE
Map-Server should not be mandatory config

### ISSUE THREAD

**Issue by ljakab** [LISPmob/lispmob#72]
With SDN controllers such as OpenDaylight it is now possible to configure an overlay entirely using REST interfaces, without the need for data plane elements to inform the control plane about current EID-to-RLOC mappings. In such cases configuring a Map-Server in LISPmob is not needed. However, the current code enforces the existence of a 'map-server' section, which results in undesired traffic.

As the subject line says, I would suggest making the 'map-server' section optional.

**Comment by arnatal** [comment]
Already on it! We are working towards making most of the sections that can be configured via NETCONF on runtime to be optional in the conf file.

**Comment by ljakab** [comment]
Awesome!

**Comment by albert-lopez** [comment]
Fixed with commit ce13ed62aba533b8854989aa8e488642e89b7e81
