### ISSUE TITLE
AFI setting in lispd.conf.example on the experimental branch is confusing

### ISSUE THREAD

**Issue by ljakab** [LISPmob/lispmob#73]
In the `rloc-iface` and `rtr-iface` sections there is a field called `afi` that can either take the value `4` or the value `6`. I suggest either renaming the field from `afi` to `ip_version`, or changing the options 4 and 6 to 1 and 2 respectively, according to http://www.iana.org/assignments/address-family-numbers, since in the current form it is a bit confusing.

**Comment by albert-lopez** [comment]
Closed with commit ce13ed62aba533b8854989aa8e488642e89b7e81
