### ISSUE TITLE
Poor throughput performance in lispmob 0.5

### ISSUE THREAD

**Issue by job** [LISPmob/lispmob#76]
It appears that the throughput performance on my PCEngines APU 1c4 (amd64 arch w/ Debian Jessie) is about 15% of what I could achieve with lispmob 0.4.1. The same wget of a 1000mb.bin file with lispmob 0.5 = 800 KB/sec, 0.4.1 = 9 MB/sec. 

How can I help with debugging?

**Comment by florincoras** [comment]
Hi Job, 

Does your CPU use spike? We've done some changes to the dataplane which now uses a hash table to speed up forwarding. However, we've had to replace our original implementation and perhaps this is the source of the slowdown.

**Comment by job** [comment]
Yes, CPU maxes out at 100% during the wget

**Comment by arnatal** [comment]
We have some clues on what might be happening, but it's not clear yet. We're working on it right now, give us a couple of days to do some testing. Thanks a lot for the feedback Job, we'll get back to you if we need some debugging on your side.

Alberto

**Comment by job** [comment]
Let me know if I can help by running a specific branch. It is easy for me to switch back and forth and perform tests.

**Comment by arnatal** [comment]
Cool, thanks! We'll let you know ;)

**Comment by albert-lopez** [comment]
Fixed the performance with commit 27a213c1352871a5775fd14f4b71cdc7be5ba1e8

**Comment by job** [comment]
Wow that was a big improvement! 0.5.1 is probably the best performing release so far! Great work guys
