### ISSUE TITLE
lispd cores when no config file

### ISSUE THREAD

**Issue by jaredmauch** [LISPmob/lispmob#80]
[jared@r204 lispmob]# limit coredumpsize unlimited
[jared@r204 lispmob]# lispd
[2015/11/29 0:7:19] INFO: LISPmob v0.5 compiled for Linux

[2015/11/29 0:7:19] WARNING: Rights: Effective [4294967295] Permitted  [4294967295]
[2015/11/29 0:7:19] INFO: Building address to interface hash table
[2015/11/29 0:7:19] INFO: Control created!
[2015/11/29 0:7:19] CRIT: Couldn't find config file /etc/lispd.conf, exiting...
Segmentation fault (core dumped)
[jared@r204 lispmob]# ls
android  AUTHORS  core.1059  FAQ.md  LICENSE  LICENSE_HISTORY  lispd  Makefile  netconf  openWRT  README.android.md  README.md  tests
[jared@r204 lispmob]# gdb lispd core.1059 
GNU gdb (GDB) Fedora 7.10-29.fc23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from lispd...done.
[New LWP 1059]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `lispd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004375da in ttable_uninit (tt=0x6667a0 <ttable>) at lib/ttable.c:84
84	    for (k = kh_begin(tt->htable); k != kh_end(tt->htable); ++k){
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.22-5.fc23.x86_64 libconfuse-2.7-9.fc23.x86_64 libgcc-5.1.1-4.fc23.x86_64 libsodium-1.0.5-1.fc23.x86_64 libstdc++-5.1.1-4.fc23.x86_64 libxml2-2.9.3-1.fc23.x86_64 xz-libs-5.2.1-3.fc23.x86_64 zeromq-4.1.2-1.fc23.x86_64 zlib-1.2.8-9.fc23.x86_64
(gdb) print k
$1 = 0
(gdb) print tt
$2 = (ttable_t *) 0x6667a0 <ttable>
(gdb) bt
#0  0x00000000004375da in ttable_uninit (tt=0x6667a0 <ttable>) at lib/ttable.c:84
#1  0x000000000040fead in tun_output_uninit () at data-plane/tun/tun_output.c:54
#2  0x0000000000410767 in tun_uninit_data_plane () at data-plane/tun/tun.c:139
#3  0x000000000043a9a6 in exit_cleanup () at lispd.c:269
#4  0x0000000000444272 in handle_config_file (lispdconf_conf_file=0x666668 <config_file>) at lispd_config_confuse.c:1097
#5  0x000000000043ac5f in parse_config_file () at lispd.c:393
#6  0x000000000043ada1 in main (argc=1, argv=0x7ffc6215b748) at lispd.c:463
(gdb) up
#1  0x000000000040fead in tun_output_uninit () at data-plane/tun/tun_output.c:54
54	    ttable_uninit(&ttable);
(gdb) print ttable
$3 = {htable = 0x0, head_list = {prev = 0x0, next = 0x0}}
(gdb) quit

**Comment by albert-lopez** [comment]
This is already fixed in testing branch. Thanks for your testing effort and notification :)
